/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedEventsRouteImport } from './routes/_authed/events'
import { Route as AuthedActivitiesRouteImport } from './routes/_authed/activities'
import { Route as ApiWebhooksStravaRouteImport } from './routes/api/webhooks/strava'
import { Route as ApiWebhooksHevyRouteImport } from './routes/api/webhooks/hevy'
import { Route as ApiStravaCallbackRouteImport } from './routes/api/strava/callback'
import { Route as ApiPlanningChatStreamRouteImport } from './routes/api/planning-chat/stream'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEventsRoute = AuthedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActivitiesRoute = AuthedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiWebhooksStravaRoute = ApiWebhooksStravaRouteImport.update({
  id: '/api/webhooks/strava',
  path: '/api/webhooks/strava',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksHevyRoute = ApiWebhooksHevyRouteImport.update({
  id: '/api/webhooks/hevy',
  path: '/api/webhooks/hevy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStravaCallbackRoute = ApiStravaCallbackRouteImport.update({
  id: '/api/strava/callback',
  path: '/api/strava/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanningChatStreamRoute = ApiPlanningChatStreamRouteImport.update({
  id: '/api/planning-chat/stream',
  path: '/api/planning-chat/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/activities': typeof AuthedActivitiesRoute
  '/events': typeof AuthedEventsRoute
  '/settings': typeof AuthedSettingsRoute
  '/api/planning-chat/stream': typeof ApiPlanningChatStreamRoute
  '/api/strava/callback': typeof ApiStravaCallbackRoute
  '/api/webhooks/hevy': typeof ApiWebhooksHevyRoute
  '/api/webhooks/strava': typeof ApiWebhooksStravaRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/activities': typeof AuthedActivitiesRoute
  '/events': typeof AuthedEventsRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
  '/api/planning-chat/stream': typeof ApiPlanningChatStreamRoute
  '/api/strava/callback': typeof ApiStravaCallbackRoute
  '/api/webhooks/hevy': typeof ApiWebhooksHevyRoute
  '/api/webhooks/strava': typeof ApiWebhooksStravaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/activities': typeof AuthedActivitiesRoute
  '/_authed/events': typeof AuthedEventsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/api/planning-chat/stream': typeof ApiPlanningChatStreamRoute
  '/api/strava/callback': typeof ApiStravaCallbackRoute
  '/api/webhooks/hevy': typeof ApiWebhooksHevyRoute
  '/api/webhooks/strava': typeof ApiWebhooksStravaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activities'
    | '/events'
    | '/settings'
    | '/api/planning-chat/stream'
    | '/api/strava/callback'
    | '/api/webhooks/hevy'
    | '/api/webhooks/strava'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/activities'
    | '/events'
    | '/settings'
    | '/'
    | '/api/planning-chat/stream'
    | '/api/strava/callback'
    | '/api/webhooks/hevy'
    | '/api/webhooks/strava'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/activities'
    | '/_authed/events'
    | '/_authed/settings'
    | '/_authed/'
    | '/api/planning-chat/stream'
    | '/api/strava/callback'
    | '/api/webhooks/hevy'
    | '/api/webhooks/strava'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPlanningChatStreamRoute: typeof ApiPlanningChatStreamRoute
  ApiStravaCallbackRoute: typeof ApiStravaCallbackRoute
  ApiWebhooksHevyRoute: typeof ApiWebhooksHevyRoute
  ApiWebhooksStravaRoute: typeof ApiWebhooksStravaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/events': {
      id: '/_authed/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthedEventsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/activities': {
      id: '/_authed/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthedActivitiesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/webhooks/strava': {
      id: '/api/webhooks/strava'
      path: '/api/webhooks/strava'
      fullPath: '/api/webhooks/strava'
      preLoaderRoute: typeof ApiWebhooksStravaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/hevy': {
      id: '/api/webhooks/hevy'
      path: '/api/webhooks/hevy'
      fullPath: '/api/webhooks/hevy'
      preLoaderRoute: typeof ApiWebhooksHevyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strava/callback': {
      id: '/api/strava/callback'
      path: '/api/strava/callback'
      fullPath: '/api/strava/callback'
      preLoaderRoute: typeof ApiStravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/planning-chat/stream': {
      id: '/api/planning-chat/stream'
      path: '/api/planning-chat/stream'
      fullPath: '/api/planning-chat/stream'
      preLoaderRoute: typeof ApiPlanningChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedActivitiesRoute: typeof AuthedActivitiesRoute
  AuthedEventsRoute: typeof AuthedEventsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedActivitiesRoute: AuthedActivitiesRoute,
  AuthedEventsRoute: AuthedEventsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPlanningChatStreamRoute: ApiPlanningChatStreamRoute,
  ApiStravaCallbackRoute: ApiStravaCallbackRoute,
  ApiWebhooksHevyRoute: ApiWebhooksHevyRoute,
  ApiWebhooksStravaRoute: ApiWebhooksStravaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
