/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedActivitiesRouteImport } from './routes/_authed/activities'
import { Route as ApiStravaStatusRouteImport } from './routes/api/strava/status'
import { Route as ApiStravaCallbackRouteImport } from './routes/api/strava/callback'
import { Route as ApiStravaActivitiesRouteImport } from './routes/api/strava/activities'
import { Route as ApiHevyWorkoutsRouteImport } from './routes/api/hevy/workouts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActivitiesRoute = AuthedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiStravaStatusRoute = ApiStravaStatusRouteImport.update({
  id: '/api/strava/status',
  path: '/api/strava/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStravaCallbackRoute = ApiStravaCallbackRouteImport.update({
  id: '/api/strava/callback',
  path: '/api/strava/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStravaActivitiesRoute = ApiStravaActivitiesRouteImport.update({
  id: '/api/strava/activities',
  path: '/api/strava/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHevyWorkoutsRoute = ApiHevyWorkoutsRouteImport.update({
  id: '/api/hevy/workouts',
  path: '/api/hevy/workouts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/activities': typeof AuthedActivitiesRoute
  '/settings': typeof AuthedSettingsRoute
  '/api/hevy/workouts': typeof ApiHevyWorkoutsRoute
  '/api/strava/activities': typeof ApiStravaActivitiesRoute
  '/api/strava/callback': typeof ApiStravaCallbackRoute
  '/api/strava/status': typeof ApiStravaStatusRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/activities': typeof AuthedActivitiesRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
  '/api/hevy/workouts': typeof ApiHevyWorkoutsRoute
  '/api/strava/activities': typeof ApiStravaActivitiesRoute
  '/api/strava/callback': typeof ApiStravaCallbackRoute
  '/api/strava/status': typeof ApiStravaStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/activities': typeof AuthedActivitiesRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/api/hevy/workouts': typeof ApiHevyWorkoutsRoute
  '/api/strava/activities': typeof ApiStravaActivitiesRoute
  '/api/strava/callback': typeof ApiStravaCallbackRoute
  '/api/strava/status': typeof ApiStravaStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activities'
    | '/settings'
    | '/api/hevy/workouts'
    | '/api/strava/activities'
    | '/api/strava/callback'
    | '/api/strava/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/activities'
    | '/settings'
    | '/'
    | '/api/hevy/workouts'
    | '/api/strava/activities'
    | '/api/strava/callback'
    | '/api/strava/status'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/activities'
    | '/_authed/settings'
    | '/_authed/'
    | '/api/hevy/workouts'
    | '/api/strava/activities'
    | '/api/strava/callback'
    | '/api/strava/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHevyWorkoutsRoute: typeof ApiHevyWorkoutsRoute
  ApiStravaActivitiesRoute: typeof ApiStravaActivitiesRoute
  ApiStravaCallbackRoute: typeof ApiStravaCallbackRoute
  ApiStravaStatusRoute: typeof ApiStravaStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/activities': {
      id: '/_authed/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthedActivitiesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/strava/status': {
      id: '/api/strava/status'
      path: '/api/strava/status'
      fullPath: '/api/strava/status'
      preLoaderRoute: typeof ApiStravaStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strava/callback': {
      id: '/api/strava/callback'
      path: '/api/strava/callback'
      fullPath: '/api/strava/callback'
      preLoaderRoute: typeof ApiStravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/strava/activities': {
      id: '/api/strava/activities'
      path: '/api/strava/activities'
      fullPath: '/api/strava/activities'
      preLoaderRoute: typeof ApiStravaActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hevy/workouts': {
      id: '/api/hevy/workouts'
      path: '/api/hevy/workouts'
      fullPath: '/api/hevy/workouts'
      preLoaderRoute: typeof ApiHevyWorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedActivitiesRoute: typeof AuthedActivitiesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedActivitiesRoute: AuthedActivitiesRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHevyWorkoutsRoute: ApiHevyWorkoutsRoute,
  ApiStravaActivitiesRoute: ApiStravaActivitiesRoute,
  ApiStravaCallbackRoute: ApiStravaCallbackRoute,
  ApiStravaStatusRoute: ApiStravaStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
